### ISSUE TITLE
`_allow_empty` rename to `allow_empty` or change to `on_empty`?

### ISSUE THREAD

**Issue by mathause** [mathause/filefinder#105]
For the `_allow_empty` keyword I initially added the underscore to make a name conflict with a placeholder less likely. This was exaggerated to begin with but after #99 we can change it with confidence. But what should we do exactly?

1. leave it be
   - no work, but I am no fan of the underscore
3. rename to `allow_empty`
   - definitely a better name, but maybe a bit overkill
4. rename to `on_empty` with the options `"raise" | "warn" | "???"`
   - would align with `on_parse_error` & add an option ("warn")
   - but what name should the third option be? (`"ignore"` seems wrong)
4. something else?

@veni-vidi-vici-dormivi I am asking once again for your opinion :man_shrugging:

**Comment by veni-vidi-vici-dormivi** [comment]
I like `on_empty` and `"raise" | "warn" | "pass"`?
