### ISSUE TITLE
method/ keyword to require exactly one match

### ISSUE THREAD

**Issue by mathause** [mathause/filefinder#98]
A pattern I often do is:

```python
fc = ff.find_files(...)

if len(fc) > 1:
    raise ValueError("More than one simulation found - please adapt your query")
```

It would be nice to move this functionality into filefinder itself. Either using a keyword (but what?) or a separate method. How about:

```python
ff.find_single_file(...)
ff.find_single_path(...)
```

?

---

`find_files` looks like:

https://github.com/mathause/filefinder/blob/dc449bd57d0d2ad084ac42f37830a0dabeedd65d/filefinder/_filefinder.py#L386-L388

it has the `on_parse_error` and `_allow_empty` keywords. But I think both should error, so we won't add them to the signature and the method should look something like:

```python

    def find_single_file(self, keys=None, **keys_kwargs):

        fc = self.full.find(
            keys=keys, on_parse_error="raise", _allow_empty=False, **keys_kwargs
        )

        if len(fc) > 1:
            raise ValueError(
                "More than one file found - please adapt your query or use `find_files`")

```

cc @veni-vidi-vici-dormivi

**Comment by mathause** [comment]
we could use a positional-only argument for `keys`

```python
def test(keys, /, **kwargs):
    print(keys, kwargs)

test({"a": 5}, keys=7) # works
# {'a': 5} {'keys': 7}


def test(keys, **kwargs):
    print(keys, kwargs)

test({"a": 5}, keys=7) # fails
# TypeError: test() got multiple values for argument 'keys'
```

I don't think `on_parse_error` and `_allow_empty` are ever going to be used, but still good to have them error. We could also rename `_allow_empty` to `allow_empty` (but that't a separate issue & PR).

**Comment by veni-vidi-vici-dormivi** [comment]
I think this is cool, personally I would prefer a separate method, and yes, it makes sense to set `on_parse_error` and `_allow_empty` as you did.
